version: "3"
services:
  database:
    image: mysql:latest
    volumes:
      - "./.data/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/site.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./:/var/www/html/"
    links:
      - php
  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    volumes:
      - "./:/var/www/html:cached"
    links:
      - database